In [1]:
import numpy as np

In [137]:
XX = [[3,5,9],[1,7,3],[20,30,40]]
xy = [*range(0,10,1)]
print(XX)
print(xy)

[[3, 5, 9], [1, 7, 3], [20, 30, 40]]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [141]:
ex1 = XX[1][1]
ex6 = XX[:][::1]
ex2 = [xy[2],xy[3],xy[5]]
ex3 = xy[:5:]
ex4 = xy[::2]
ex5 = xy[5::]
print('\...', ex1,'\...', ex6, '\...', ex2,'\...', ex3, '\...', ex4, '\...', ex5)

\... 7 \... [[3, 5, 9], [1, 7, 3], [20, 30, 40]] \... [2, 3, 5] \... [0, 1, 2, 3, 4] \... [0, 2, 4, 6, 8] \... [5, 6, 7, 8, 9]


In [8]:
XX[:][2]

[20, 30, 40]

In [56]:
X = np.array([[3,5,9],[1,7,3],[20,30,40]])
ex8 = X[0:2,1:3]
print(X, '\n', '\n', ex8)


[[ 3  5  9]
 [ 1  7  3]
 [20 30 40]] 
 
 [[5 9]
 [7 3]]


In [9]:
Y = np.arange(10)
Y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
YY = np.arange(-4,11,2, dtype=np.int8)   # (start, end, step) and reshape to change matix dimensions
siz = YY.size
YY1 = YY.reshape(2, 4)
siz1 = YY1.size
print(YY, '\n', siz, '\n', YY1, '\n', siz1, '\n')
## to learn about some of the possible operations on the matices using numpy
e1 = len(YY)
e2 = YY1.shape
e3 = YY.shape
e4 = np.amax(YY1)
e5 = np.argmax(YY1)
e6 = np.average(YY1)
e7 = np.amin(YY1)
e8 = np.argmin(YY1)
e9 = abs(YY)
e10 = len(YY1)
print(e1, '\n', e2, '\n', e3, '\n', e4, '\n', e5, '\n', e6, '\n', e7, '\n', e8, '\n', e9, '\n', e10)

AttributeError: 'int' object has no attribute 'dtype'

In [68]:
ff = np.zeros((3,4,4), np.float32)
ff

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)

In [16]:
ff[0:3:2,:,:] = 2
ff

array([[[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]]], dtype=float32)

In [136]:
# example on array using numpy
d = np.random.randint(2, high=8, size=(3,4)) # Generate a random numbers (lowest value, highest, size)
dd = np.random.randint(3, high=9, size=(4,3))
# matices math on numpy
d1 = np.dot(d,dd) # matrix multiblication
d2 = np.add(d, dd.reshape(3,4)) # elementwise addition
d3 = np.subtract(d, dd.reshape(3,4)) # elementwise subtraction
# d4 = np.divide(d, dd.reshape(3,4))
d4 = np.multiply(d, dd.reshape(3,4))  # elementwise multiblication
# d5 = np.transpose(dd)
d5 = dd.T # transpose with classic modules
d6 = np.resize(dd, (3,3)) # matice resizing
d7 = np.sum(dd, axis=0) # summation of matix elements in column direction
# d7 = np.sum(dd, axis=1) # summation of matix elements in row direction
# d7 = np.linalg.inv(d6) # inverse of the matix
print(d, '\n\n', dd,'\n\n **1-', d1,'\n **2- ', d2,'\n **3- ', d3,'\n **4- ', d4,'\n **5- ', d5, '\n **6- ', d6, '\n **7- ', d7)

[[4 3 2 7]
 [3 7 6 4]
 [5 5 7 3]] 

 [[6 3 5]
 [4 7 6]
 [8 7 6]
 [7 4 4]] 

 **1- [[101  75  78]
 [122 116 109]
 [127 111 109]] 
 **2-  [[10  6  7 11]
 [10 13 14 11]
 [11 12 11  7]] 
 **3-  [[-2  0 -3  3]
 [-4  1 -2 -3]
 [-1 -2  3 -1]] 
 **4-  [[24  9 10 28]
 [21 42 48 28]
 [30 35 28 12]] 
 **5-  [[6 4 8 7]
 [3 7 7 4]
 [5 6 6 4]] 
 **6-  [[6 3 5]
 [4 7 6]
 [8 7 6]] 
 **7-  [25 21 21]
