In [1]:
import numpy as np

In [8]:
X = np.array([[3,5,9],[1,7,3],[20,30,40]])
X

array([[ 3,  5,  9],
       [ 1,  7,  3],
       [20, 30, 40]])

In [26]:
X[0:2,1:2]

array([[5],
       [7]])

In [45]:
X[1][1]
X[1,1]

7

In [46]:
X[[1,1],[1,2]]

array([7, 3])

In [29]:
XX = [[3,5,9],[1,7,3],[20,30,40]]
XX

[[3, 5, 9], [1, 7, 3], [20, 30, 40]]

In [43]:
ex1 = XX[1][1]

7

In [33]:
XX[:][2]

[20, 30, 40]

In [52]:
Y = np.arange(10)
Y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
YY = np.arange(0,11,2).reshape(2,3)   # (start, end, step) and reshape to change matix dimensions
siz = YY.size
print(YY)
print('..............',siz)

[[ 0  2  4]
 [ 6  8 10]]
.............. 6


In [88]:
ff = np.zeros((3,4,4), np.float32)
ff

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)

In [89]:
ff[1,:,:] = 2
ff

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)