In [1]:
import numpy as np

In [2]:
X = [[3,5,9], [5,8,7], [15,12,36]]
Y = [*range(0,11,1)]
print(X,'\n\n', Y)

[[3, 5, 9], [5, 8, 7], [15, 12, 36]] 

 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [3]:
ex1 = X[0][2]
ex2 = X[1][:]
print(ex1,'\n', ex2)

9 
 [5, 8, 7]


In [4]:
ex4 = Y[3::]
ex4

[3, 4, 5, 6, 7, 8, 9, 10]

In [5]:
X = np.array([[3,5,9], [5,8,7], [10,20,30]])
X

array([[ 3,  5,  9],
       [ 5,  8,  7],
       [10, 20, 30]])

In [6]:
ex5 = X[0:2, :]
ex5

array([[3, 5, 9],
       [5, 8, 7]])

In [7]:
Y = np.arange(-4, 11, 2, dtype=np.int8)
YY = len(Y)
siz = Y.size
Y1 = Y.reshape(2,4)
siz1 = Y1.size
print(Y,'\n', siz,'\n', Y1,'\n',siz1)

[-4 -2  0  2  4  6  8 10] 
 8 
 [[-4 -2  0  2]
 [ 4  6  8 10]] 
 8


In [8]:
e1 =Y1.shape
e2 = np.amax(Y1)
e3 = np.argmax(Y1)
e4 = np.average(Y1)
e5 = np.amin(Y1)
e6 = np.argmin(Y1)
e8 = np.abs(Y)
print(e4,'\n',e5,'\n',e8)

3.0 
 -4 
 [ 4  2  0  2  4  6  8 10]


In [14]:
F = np.zeros((3,4,4), np.int8)
F

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int8)

In [17]:
F[0,1,:] = 10
F

array([[[ 2,  2,  2,  2],
        [10, 10, 10, 10],
        [ 2,  2,  2,  2],
        [ 2,  2,  2,  2]],

       [[ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[ 5,  5,  5,  5],
        [ 5,  5,  5,  5],
        [ 5,  5,  5,  5],
        [ 5,  5,  5,  5]]], dtype=int8)

In [18]:
d = np.random.randint(2, high=8, size=(3,4))
dd = np.random.randint(3, high=9, size=(4,3))
print(d,'\n\n',dd)

[[5 7 4 5]
 [6 2 4 4]
 [3 4 7 4]] 

 [[7 7 4]
 [5 3 5]
 [4 6 7]
 [7 6 7]]


In [30]:
d1 = np.dot(d,dd)
d2 = np.add(d, dd.T)
d3 = np.subtract(d, dd.T)
d4 = np.multiply(d, dd.T)
d5 = dd.T
d6 = np.sum(d, axis=1)
d7 = np.resize(dd, (6,3))
print(d7)

[[7 7 4]
 [5 3 5]
 [4 6 7]
 [7 6 7]
 [7 7 4]
 [5 3 5]]
